apiVersion: vra.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: allianz-next-creds-jet
spec:
  credentials:
    source: Secret
    secretRef:
      name: allianz-next-creds-jet
      namespace: crossplane-system
      key: credentials
