apiVersion: catalogsourceblueprint.vra.jet.crossplane.io/v1alpha1
kind: SourceBlueprint
metadata:
  name: catalog-source-blueprint-test-1
spec:
  forProvider:
    name: catalog-source-blueprint-test-1
    projectId: 1622eaa5-1fa6-4b67-9546-915173b1a570

  providerConfigRef:
    name: default