apiVersion: blueprint.vra.jet.crossplane.io/v1alpha1
kind: Blueprint
metadata:
  name: vra-blueprint-test-01
  namespace: crossplane-system
spec:
  forProvider:
    name: vra-blueprint-test-01
    description: "Managed by Crossplane vRA Jet provider"

    projectIdRef:
      name: vra-project-test

    content: "formatVersion: 1"

  providerConfigRef:
    name: allianz-next-creds-jet