apiVersion: deployment.vra.jet.crossplane.io/v1alpha1
kind: Deployment
metadata:
  name: vra-deployment-ankasoft-1
spec:
  forProvider:
    name: vra-deployment-ankasoft-1
    description: "Managed with Crossplane vRA Provider"

    catalogItemId: cd5c57f5-1cfd-356e-97f3-6e81b0068ced
    catalogItemVersion: "2"
    projectId: a24427ee-cae9-41c1-abcf-c88d99779e10

    inputs:
        input1: test1
        input2: test2

  providerConfigRef:
    name: default